In [1]:
import faiss, json , os , numpy as np 

In [2]:
document = """ Kipi.ai: A leader in AI and Data Analytics Solutions
Kipi.ai, a WNS company, is a prominent player in the field of advanced analytics and AI services. They focus on AI, machine learning, and data science to empower businesses with data-driven insights and innovation. 
Key areas of expertise
Snowflake Partnership: Kipi.ai is an Elite Snowflake Partner with one of the largest global teams certified in Snowflake technology. They use the Snowflake AI Data Cloud to deliver scalable, AI-driven solutions.
AI and Machine Learning: Kipi.ai specializes in integrating AI and Machine Learning technologies into data systems, providing businesses with a competitive edge.
Data Modernization and Democratization: Kipi.ai assists businesses in modernizing their data infrastructure and making data accessible to all stakeholders, thus facilitating data-driven decision-making.
Comprehensive Service Portfolio: Their services include strategic advisory, data engineering, business intelligence, advanced analytics, cost and performance optimization, and AI and machine learning solutions.
Industry Focus: Kipi.ai serves a diverse range of industries, including:
Healthcare
Financial Services
Technology
Manufacturing
Retail & Consumer Packaged Goods (CPG)
Professional Services
Media and Entertainment 
Awards and Recognition
Kipi.ai has received several accolades, including being named the Global Innovation Partner of the Year at Snowflake Summit 2025. They have also been recognized as the Americas Innovation Partner of the Year (2024), UK&I Partner of the Year (2024), and Americas System Integrator Growth Partner of the Year (2023) by Snowflake. 
Acquisition by WNS
In March 2025, WNS (Holdings) Limited, a digital-led business transformation and services company, acquired Kipi.ai. This acquisition aims to strengthen WNS's capabilities in AI and data analytics and expand Kipi.ai's global reach and service offerings."""

In [3]:
clean_data = document.replace("\n", " ").replace("  ", " ")
clean_data = clean_data.strip()

In [4]:
len(clean_data)

1915

In [8]:
max_characters = 300
overlap = 100
chunks = []
i=0

while i < len(clean_data):
    chunk = clean_data[i:i+max_characters]
    if len(chunk) < max_characters:
        chunks.append(chunk)
        break
    else:
        chunks.append(chunk)
        i += (max_characters - overlap)

In [9]:
len(chunks)

10

In [13]:
print(chunks[1])

nce to empower businesses with data-driven insights and innovation. Key areas of expertise Snowflake Partnership: Kipi.ai is an Elite Snowflake Partner with one of the largest global teams certified in Snowflake technology. They use the Snowflake AI Data Cloud to deliver scalable, AI-driven solution


In [15]:

import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-f4e83f0aa89b0a11018f8eb8194fb41b3e09855d7cdbb3619b4f7f0bb93e26d3"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding

In [16]:
embeddings = []
for chunk in chunks:
    embeddings.append(generate_embeddings(chunk))

In [17]:
embeddings

[array([ 0.0036385 , -0.0196634 ,  0.02835599, ..., -0.00165474,
         0.03970282,  0.03078904], shape=(1536,)),
 array([ 0.02508548, -0.0043241 ,  0.03335567, ..., -0.02657457,
         0.02207293,  0.03365349], shape=(1536,)),
 array([-0.00073398, -0.00371744,  0.01080108, ..., -0.0211104 ,
         0.01024492,  0.01882724], shape=(1536,)),
 array([ 0.00426726,  0.00508446,  0.03133286, ...,  0.00312913,
        -0.0063474 ,  0.03009667], shape=(1536,)),
 array([ 0.01660021, -0.01831577,  0.0432963 , ..., -0.00415005,
         0.00030277,  0.03769296], shape=(1536,)),
 array([-0.00952798, -0.02323869,  0.0425407 , ..., -0.02994334,
         0.01380297,  0.02910679], shape=(1536,)),
 array([ 0.00624067, -0.02861948, -0.00017746, ..., -0.03509505,
         0.04449097,  0.01585879], shape=(1536,)),
 array([-0.0283985 , -0.03522183,  0.03805688, ..., -0.04199711,
         0.03964258,  0.00244463], shape=(1536,)),
 array([-0.03266507, -0.02372503,  0.02230844, ..., -0.03790291,
       

In [19]:
embeddings[0].shape

(1536,)

In [20]:
embeddings = np.array(embeddings , dtype=np.float32)

In [22]:
embeddings.shape

(10, 1536)