In [ ]:
EURI_API_KEY="euri-f4e83f0aa89b0a11018f8eb8194fb41b3e09855d7cdbb3619b4f7f0bb93e26d3"

In [8]:

import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-f4e83f0aa89b0a11018f8eb8194fb41b3e09855d7cdbb3619b4f7f0bb93e26d3"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding

text = "The weather is sunny today."

embedding = generate_embeddings(text)

In [12]:
embedding_length = len(embedding)
print(f"Embedding length: {embedding_length}")
print(f"Embedding: {embedding}")

Embedding length: 1536
Embedding: [ 0.01067466 -0.03126568  0.00883722 ... -0.03035571  0.01221461
  0.02594584]


In [15]:
from sentence_transformers import SentenceTransformer
sentences = ["This is an example sentence", "Each sentence is converted"]

model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
embeddings = model.encode(sentences)
print(embeddings)


[[ 6.76568225e-02  6.34958744e-02  4.87131104e-02  7.93049634e-02
   3.74480337e-02  2.65282183e-03  3.93749177e-02 -7.09844753e-03
   5.93614280e-02  3.15369926e-02  6.00980930e-02 -5.29051796e-02
   4.06067334e-02 -2.59308163e-02  2.98427846e-02  1.12693023e-03
   7.35149682e-02 -5.03819361e-02 -1.22386575e-01  2.37028431e-02
   2.97265332e-02  4.24769148e-02  2.56337635e-02  1.99519214e-03
  -5.69190718e-02 -2.71598455e-02 -3.29035372e-02  6.60248920e-02
   1.19007140e-01 -4.58791889e-02 -7.26214945e-02 -3.25839370e-02
   5.23414016e-02  4.50552553e-02  8.25295597e-03  3.67023721e-02
  -1.39415478e-02  6.53919056e-02 -2.64272522e-02  2.06379511e-04
  -1.36643611e-02 -3.62809934e-02 -1.95043404e-02 -2.89738160e-02
   3.94270830e-02 -8.84091258e-02  2.62424489e-03  1.36713833e-02
   4.83063050e-02 -3.11565641e-02 -1.17329143e-01 -5.11690639e-02
  -8.85287747e-02 -2.18961909e-02  1.42986337e-02  4.44167703e-02
  -1.34814745e-02  7.43392259e-02  2.66382899e-02 -1.98762454e-02
   1.79190

In [18]:
print("Embeddings generated successfully.")
print(len(embeddings[0]))  # Print the length of the first embedding

Embeddings generated successfully.
384


In [20]:
documents=[
    "My name is Gautham Pai",
    "I am a student at Euron",
    "I am learning about embeddings",
    "Embeddings are useful for NLP tasks",
    "I enjoy coding in Python",
    "Gautham is my name"
]

document_embeddings = model.encode(documents)
document_embeddings

array([[-0.10474794,  0.01786744, -0.01762569, ..., -0.04669027,
        -0.0730947 , -0.01343723],
       [ 0.01141534, -0.03312049,  0.00760856, ..., -0.01491088,
        -0.05414159, -0.01280098],
       [-0.01038813, -0.1177768 ,  0.01302758, ...,  0.07614405,
         0.05566344,  0.00541477],
       [-0.03576271, -0.04729838,  0.07020186, ...,  0.10271112,
         0.04191924,  0.03304788],
       [-0.05741466, -0.00085518, -0.04412755, ...,  0.13519098,
         0.099519  , -0.03394092],
       [-0.05801065,  0.03986489, -0.05599007, ..., -0.07954406,
        -0.0630101 ,  0.03209325]], shape=(6, 384), dtype=float32)

### using formula

In [21]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix = cosine_similarity(document_embeddings)
print("Cosine Similarity Matrix:")
print(similarity_matrix)

Cosine Similarity Matrix:
[[ 1.          0.18295816  0.0074681  -0.02531892  0.15075442  0.7579996 ]
 [ 0.18295816  0.9999999   0.20679098  0.11530283  0.211982    0.00403254]
 [ 0.0074681   0.20679098  1.          0.6873878   0.21950354  0.04948063]
 [-0.02531892  0.11530283  0.6873878   1.0000002   0.16466527 -0.0209741 ]
 [ 0.15075442  0.211982    0.21950354  0.16466527  1.0000001   0.08286315]
 [ 0.7579996   0.00403254  0.04948063 -0.0209741   0.08286315  1.        ]]


### manual

In [22]:
from numpy import dot
from numpy.linalg import norm
def cosine_similarity_manual(a, b):
    return dot(a, b) / (norm(a) * norm(b))

In [25]:
cosine_sim = cosine_similarity_manual(document_embeddings[0], document_embeddings[5])
print(f"Cosine Similarity (manual): {cosine_sim}")

Cosine Similarity (manual): 0.75799959897995
