In [1]:
pip install faiss-cpu

  Using cached faiss_cpu-1.12.0-cp310-cp310-win_amd64.whl.metadata (5.2 kB)
  Using cached numpy-2.2.6-cp310-cp310-win_amd64.whl.metadata (60 kB)
Using cached faiss_cpu-1.12.0-cp310-cp310-win_amd64.whl (18.2 MB)
Using cached numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)

   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   -------------------- ------------------- 1/2 [faiss-cpu]
   -------------------- ------------------- 1/2 [f

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
easyocr 1.7.2 requires opencv-python-headless, which is not installed.
easyocr 1.7.2 requires Pillow, which is not installed.
easyocr 1.7.2 requires pyclipper, which is not installed.
easyocr 1.7.2 requires python-bidi, which is not installed.
easyocr 1.7.2 requires PyYAML, which is not installed.
easyocr 1.7.2 requires scipy, which is not installed.
easyocr 1.7.2 requires Shapely, which is not installed.
easyocr 1.7.2 requires torch, which is not installed.
easyocr 1.7.2 requires torchvision>=0.5, which is not installed.
imageio 2.37.0 requires pillow>=8.3.2, which is not installed.
scikit-image 0.25.2 requires networkx>=3.0, which is not installed.
scikit-image 0.25.2 requires pillow>=10.1, which i

In [2]:
pip install numpy requests

  Using cached requests-2.32.4-py3-none-any.whl.metadata (4.9 kB)
  Using cached charset_normalizer-3.4.3-cp310-cp310-win_amd64.whl.metadata (37 kB)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
  Using cached urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)
  Using cached certifi-2025.8.3-py3-none-any.whl.metadata (2.4 kB)
Using cached requests-2.32.4-py3-none-any.whl (64 kB)
Using cached charset_normalizer-3.4.3-cp310-cp310-win_amd64.whl (107 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached urllib3-2.5.0-py3-none-any.whl (129 kB)
Using cached certifi-2025.8.3-py3-none-any.whl (161 kB)

   ---------------- ----------------------- 2/5 [charset_normalizer]
   ---------------------------------------- 5/5 [requests]

Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [3]:
data = """
Making an Impact
Helping Millions of Students Succeed
Sudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.

In 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world.

The Entrepreneur and Teacher: Sudhanshu's Dual Legacy
Sudhanshu's journey isn't just one of entrepreneurial success; it's also a story of dedication to teaching. Throughout his career, he has remained a passionate educator, constantly looking for ways to empower others through knowledge. Whether teaching courses in Big Data, Data Science, or programming, Sudhanshu has always sought to make complex subjects accessible to learners at all levels.

His commitment to affordable education has earned him the respect and admiration of countless students. Many credit Sudhanshu with changing their lives, helping them secure jobs, improve their skills, and break free from the limitations of their backgrounds."""

In [6]:
clean_data = data.strip()
len(clean_data)

1498

In [10]:
max_char = 300
overlap = 100
chunks = []
i = 0
while i <len(clean_data):
    piece = clean_data[i:i+max_char]
    chunks.append(piece)
    i = i+max_char - overlap

In [11]:
len(chunks)

8

In [12]:
chunks

["Making an Impact\nHelping Millions of Students Succeed\nSudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in toda",
 "1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 20",
 'backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron',
 "ignificant milestone, Sudhanshu remained focused on his mission. Even after t

In [13]:

import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-e4ac18a3dd84d7880024dceca11b980a88964d6e7faa2ed7c854d0ab6fea2bfd"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding

In [14]:
for i in chunks:
    embedding = generate_embeddings(i)
    print(embedding)

[ 0.01636502 -0.01330146  0.04360536 ... -0.00716132 -0.00025957
  0.00777273]
[-0.02781193  0.00343053  0.04798149 ... -0.01521909 -0.01743826
 -0.00741914]
[-0.02119237 -0.03513358  0.01877532 ... -0.01876093  0.00953153
  0.02064566]
[ 0.00014624 -0.01620219  0.03854276 ... -0.03406411  0.00342815
  0.02558101]
[ 0.00538704 -0.01142304  0.04874471 ... -0.0355971   0.00306157
  0.00572053]
[-0.00912461 -0.01832682  0.04314627 ... -0.02185768 -0.00779892
 -0.01152378]
[-0.00252494 -0.02891203  0.04281055 ... -0.00076008 -0.01947349
  0.00868658]
[ 0.0317256   0.01637366  0.04584625 ... -0.01135022 -0.06958151
  0.01558773]


In [18]:
emb_list = []
meta= []
for idx,chunk in enumerate(chunks):
    vec = generate_embeddings(chunk)
    emb_list.append(vec.astype("float32"))
    
    meta.append({"id": idx, "text": chunk})
    

In [19]:
emb_list

[array([ 0.01636502, -0.01330146,  0.04360536, ..., -0.00716132,
        -0.00025957,  0.00777273], shape=(1536,), dtype=float32),
 array([-0.02781193,  0.00343053,  0.04798149, ..., -0.01521909,
        -0.01743826, -0.00741914], shape=(1536,), dtype=float32),
 array([-0.02119237, -0.03513358,  0.01877532, ..., -0.01876093,
         0.00953153,  0.02064566], shape=(1536,), dtype=float32),
 array([ 0.00011691, -0.01620286,  0.03854437, ..., -0.03406553,
         0.00343817,  0.02559526], shape=(1536,), dtype=float32),
 array([ 0.00538704, -0.01142304,  0.04874471, ..., -0.0355971 ,
         0.00306157,  0.00572053], shape=(1536,), dtype=float32),
 array([-0.00912461, -0.01832682,  0.04314627, ..., -0.02185768,
        -0.00779892, -0.01152378], shape=(1536,), dtype=float32),
 array([-0.00252494, -0.02891203,  0.04281055, ..., -0.00076008,
        -0.01947349,  0.00868658], shape=(1536,), dtype=float32),
 array([ 0.0317256 ,  0.01637366,  0.04584625, ..., -0.01135022,
        -0.0695815

In [20]:
meta

[{'id': 0,
  'text': "Making an Impact\nHelping Millions of Students Succeed\nSudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in toda"},
 {'id': 1,
  'text': "1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 20"},
 {'id': 2,
  'text': 'backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron'},
 {'id': 3,
  'te

In [21]:
type(emb_list)

list

In [25]:
xb = np.vstack(emb_list)

In [23]:
import faiss

In [26]:
faiss.normalize_L2(xb)

In [28]:
d = xb.shape[1]

In [29]:
d

1536

In [30]:
index = faiss.IndexFlatIP(1536)
index.add(xb)


In [31]:
index_path = "index_sudhanshu.faiss"
meta_path = "meta_sudhanshu.jsonl"

In [32]:
faiss.write_index(index, index_path)

In [33]:
import json,os

In [34]:
with open(meta_path, "w") as f:
    for item in meta:
        f.write(json.dumps(item) + "\n")

In [37]:
query = "who is sudhanshu"
q = generate_embeddings(query).astype("float32").reshape(1, -1)
faiss.normalize_L2(q)
index.search(q, 5)

(array([[0.5388923 , 0.50190413, 0.50101304, 0.48841798, 0.38360453]],
       dtype=float32),
 array([[4, 5, 6, 3, 1]]))

In [39]:
test = np.array([[4,5,6,7,8]], dtype=np.float32)

In [40]:
test

array([[4., 5., 6., 7., 8.]], dtype=float32)

In [41]:
np.linalg.norm(test)    

np.float32(13.784049)

In [42]:
faiss.normalize_L2(test)

In [43]:
np.linalg.norm(test)

np.float32(0.99999994)

In [45]:
emb_list[0]

array([ 0.01636502, -0.01330146,  0.04360536, ..., -0.00716132,
       -0.00025957,  0.00777273], shape=(1536,), dtype=float32)

In [46]:
emb_list[1]

array([-0.02781193,  0.00343053,  0.04798149, ..., -0.01521909,
       -0.01743826, -0.00741914], shape=(1536,), dtype=float32)

In [47]:
np.dot(emb_list[0], emb_list[1])

np.float32(0.77082086)

In [48]:
emb_list[1].shape

(1536,)