In [2]:
from qdrant_client import QdrantClient

qdrant_client = QdrantClient(
    url="https://6c0eebc7-ce87-4710-ac69-f22e5d7be677.us-east4-0.gcp.cloud.qdrant.io:6333", 
    api_key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.ACO8n1Z97x1ThipIr6_QQRTTC0hTCIvYtpQ_7PPxxIE",
)

print(qdrant_client.get_collections())

collections=[]


In [1]:

pip install qdrant-client

  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
  Using cached pydantic-2.11.7-py3-none-any.whl.metadata (67 kB)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
  Using cached h2-4.2.0-py3-none-any.whl.metadata (5.1 kB)
  Using cached hyperframe-6.1.0-py3-none-any.whl.metadata (4.3 kB)
  Using cached hpack-4.1.0-py3-none-any.whl.metadata (4.6 kB)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
  Using cached pydantic_core-2.33.2-cp310-cp310-win_amd64.whl.metadata (6.9 kB)
  Using cached typing_inspection-0.4.1-py3-none-any.whl.metadata (2.6 kB)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
   ---------------------------------------- 0.0/4.5 MB ? eta -:--:--
   ---------------------------------------- 4.5/4.5 MB 54.3 MB/s eta 0:00:00
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Using cached h11-0.1

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [4]:
qdrant_client

In [5]:
collection_name = "sudhanshu_story"

In [ ]:
from qdrant_client import models
qdrant_client.recreate_collection(collection_name=collection_name,vectors_config=models.VectorParams(size=1536,distance=models.Distance.COSINE))

C:\Users\scl\AppData\Local\Temp\ipykernel_11508\908753693.py:2: DeprecationWarning: `recreate_collection` method is deprecated and will be removed in the future. Use `collection_exists` to check collection existence and `create_collection` instead.
  qdrant_client.recreate_collection(


True

In [8]:
points = []

In [ ]:
for idx,(chunk,emb) in enumerate(zip(chunks, embeddings)):

In [11]:
data = """
Making an Impact
Helping Millions of Students Succeed
Sudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.

In 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world.

The Entrepreneur and Teacher: Sudhanshu's Dual Legacy
Sudhanshu's journey isn't just one of entrepreneurial success; it's also a story of dedication to teaching. Throughout his career, he has remained a passionate educator, constantly looking for ways to empower others through knowledge. Whether teaching courses in Big Data, Data Science, or programming, Sudhanshu has always sought to make complex subjects accessible to learners at all levels.

His commitment to affordable education has earned him the respect and admiration of countless students. Many credit Sudhanshu with changing their lives, helping them secure jobs, improve their skills, and break free from the limitations of their backgrounds."""

In [15]:
max_chars = 300
overlap = 100
chunks = []
i = 0
while i < len(data):
    piece = data[i:i+max_chars]
    if not piece:
        break
    chunks.append(piece)
    i += max_chars - overlap

In [16]:
chunks

["\nMaking an Impact\nHelping Millions of Students Succeed\nSudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in tod",
 " 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 2",
 ' backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuro',
 "significant milestone, Sudhanshu remained focused on his mission. Even after

In [19]:
import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-e4ac18a3dd84d7880024dceca11b980a88964d6e7faa2ed7c854d0ab6fea2bfd"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding

In [21]:
emb = []
for i in chunks:
     emb.append(generate_embeddings(i))


In [22]:
emb

[array([ 0.01565358, -0.01934289,  0.04531095, ..., -0.00577104,
        -0.00407253,  0.00715778], shape=(1536,)),
 array([-0.0236942 ,  0.00685956,  0.05190287, ..., -0.01408406,
        -0.01782809, -0.00044224], shape=(1536,)),
 array([-0.02825853, -0.04136273,  0.01631792, ..., -0.01450328,
         0.00928791,  0.0286464 ], shape=(1536,)),
 array([-0.00331321, -0.01448019,  0.04481963, ..., -0.03784156,
         0.00096448,  0.02355444], shape=(1536,)),
 array([ 0.01124366, -0.01139535,  0.04499993, ..., -0.03996904,
        -0.00478124, -0.00603581], shape=(1536,)),
 array([-0.00356247, -0.02536403,  0.03461257, ..., -0.01503053,
         0.00720434, -0.01452775], shape=(1536,)),
 array([ 0.00099893, -0.01808071,  0.05821489, ..., -0.00126444,
        -0.01707112,  0.00456934], shape=(1536,)),
 array([ 0.0388838 ,  0.00580014,  0.04907459, ..., -0.00530384,
        -0.06305052,  0.0170067 ], shape=(1536,))]

In [25]:
emnbeddings = np.array(
    emb
)

In [26]:
emnbeddings

array([[ 0.01565358, -0.01934289,  0.04531095, ..., -0.00577104,
        -0.00407253,  0.00715778],
       [-0.0236942 ,  0.00685956,  0.05190287, ..., -0.01408406,
        -0.01782809, -0.00044224],
       [-0.02825853, -0.04136273,  0.01631792, ..., -0.01450328,
         0.00928791,  0.0286464 ],
       ...,
       [-0.00356247, -0.02536403,  0.03461257, ..., -0.01503053,
         0.00720434, -0.01452775],
       [ 0.00099893, -0.01808071,  0.05821489, ..., -0.00126444,
        -0.01707112,  0.00456934],
       [ 0.0388838 ,  0.00580014,  0.04907459, ..., -0.00530384,
        -0.06305052,  0.0170067 ]], shape=(8, 1536))

In [27]:
points = []

for idx, (chunk,emb) in enumerate(zip(chunks, emnbeddings)):
    points.append(
        models.PointStruct(
            id=idx,
            vector=emb.astype("float32").tolist(),
            payload={"text": chunk}
        )
    )

In [28]:
points

[PointStruct(id=0, vector=[0.01565358228981495, -0.01934289000928402, 0.04531094804406166, 0.04785709083080292, 0.040816228836774826, -0.040114738047122955, 0.0027718530036509037, 0.10745761543512344, -0.02977428212761879, 0.007515018340200186, 0.06443300098180771, -0.04255695641040802, -0.05357292294502258, -0.017900941893458366, 0.009963732212781906, -0.0036081180442124605, -0.02101866900920868, -0.04476534575223923, 0.00027523672906681895, 0.048870351165533066, 0.04855857789516449, 0.03790634870529175, 0.034528814256191254, -0.00957401655614376, 0.07524111866950989, -0.03751663491129875, 0.008482811972498894, 0.012009739875793457, -0.007261703256517649, -0.05414450541138649, -0.000596752215642482, -0.01197726372629404, -0.04102407395839691, -0.014315557666122913, -0.01691366173326969, 0.004835722502321005, -0.027176177129149437, 0.004215424880385399, -0.002927739406004548, 0.021940995007753372, 0.021005677059292793, -0.02004437893629074, 0.033931247889995575, 0.03655533492565155, -0

In [29]:
qdrant_client.upsert(
    collection_name=collection_name,points=points
)

UpdateResult(operation_id=0, status=<UpdateStatus.COMPLETED: 'completed'>)

In [30]:
query ="who is sudhanshu"

In [32]:
q_resp = generate_embeddings(query)

In [33]:
q_resp

array([-0.02156985, -0.02583072, -0.00604044, ..., -0.00566746,
        0.01904114, -0.00011172], shape=(1536,))

In [35]:
q_vec = np.array(q_resp).astype("float32")

In [36]:
q_vec

array([-0.02156985, -0.02583072, -0.00604044, ..., -0.00566746,
        0.01904115, -0.00011172], shape=(1536,), dtype=float32)

In [37]:
qdrant_client.search(collection_name="sudhanshu_story", query_vector=q_vec, limit=5, with_payload=True)

C:\Users\scl\AppData\Local\Temp\ipykernel_11508\109133141.py:1: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  qdrant_client.search(collection_name="sudhanshu_story", query_vector=q_vec, limit=5, with_payload=True)


[ScoredPoint(id=6, version=0, score=0.54038566, payload={'text': 's accessible to learners at all levels.\n\nHis commitment to affordable education has earned him the respect and admiration of countless students. Many credit Sudhanshu with changing their lives, helping them secure jobs, improve their skills, and break free from the limitations of their backgrounds.'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=4, version=0, score=0.5050121, payload={'text': "epreneur and Teacher: Sudhanshu's Dual Legacy\nSudhanshu's journey isn't just one of entrepreneurial success; it's also a story of dedication to teaching. Throughout his career, he has remained a passionate educator, constantly looking for ways to empower others through knowledge. Whether teaching co"}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=5, version=0, score=0.498349, payload={'text': 'onate educator, constantly looking for ways to empower others through knowledge. Whether teaching c